/* Auto-generated by write.html on 2026-04-11T05:08:03.665Z */
window.HEE_NOTES = [
  {
    "id": "mntu9sy1-vg26rn",
    "title": "안녕",
    "date": "2026-04-11",
    "body": "안녕을 빌며, 첫 번째 글.",
    "createdAt": "2026-04-11T04:32:48.841Z",
    "updatedAt": "2026-04-11T05:08:03.664Z"
  }
];
