/* Auto-generated by write.html on 2026-04-11T08:44:33.134Z */
window.HEE_NOTES = [
  {
    "id": "mnu39jhq-3gvoun",
    "title": "영상 테스트",
    "date": "2026-04-11",
    "body": "<iframe width=\"560\" height=\"315\" src=\"https://www.youtube-nocookie.com/embed/zAv__dzhKX8\" frameborder=\"0\" allow=\"accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture\" allowfullscreen=\"\"></iframe><p></p>",
    "createdAt": "2026-04-11T08:44:33.134Z",
    "updatedAt": "2026-04-11T08:44:33.134Z"
  }
];
